export enum RoleClass {
  BEAST_TYRANT = "beast_tyrant",
  BERSERKER = "berserker",
  BRUTE = "brute",
  CRAGHEART = "cragheart",
  DOOMSTALKER = "doomstalker",
  ELEMENTALIST = "elementalist",
  MINDTHIEF = "mindthief",
  NIGHTSHROUD = "nightshroud",
  PLAGUEHERALD = "plagueherald",
  QUARTERMASTER = "quartermaster",
  SAWBONES = "sawbones",
  SCOUNDREL = "scoundrel",
  SOOTHSINGER = "soothsinger",
  SPELLWEAVER = "spellweaver",
  SUMMONER = "summoner",
  TINKERER = "tinkerer",
}
